x-deploy: &deploy-dev
  deploy:
    resources:
      limits:
        cpus: "1"
        memory: 512M
      reservations:
        memory: 256M
x-env_file: &env_file
  env_file:
    - .env
x-restart: &restart
  restart: always

services:
  mysqlneto:
    image: mariadb:10.6.4-focal
    networks: ["backend"]
    <<: [*deploy-dev, *env_file, *restart]
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST="%"
      -
  pythonmap:
    build:
      context: .
      dockerfile: Dockerfile.python
    depends_on: ["mysqlneto"]
    networks: ["backend"]
    <<: [*restart]

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
