include:
  - /DOCKER_TEST/ZhelanovNeto/proxy.yaml
services:
  mysqlneto:
    image: mariadb:10.6.4-focal
    container_name: mysqlneto
    restart: always
    env_file:
      - .env
    networks:
      backend:
        ipv4_address: 172.20.0.10
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST=%

  pythonmap:
    build:
      context: .
      dockerfile: Dockerfile.python
    depends_on: ["mysqlneto"]
    container_name: pythonmap
    restart: always
    env_file:
      - .env
    networks:
      backend:
        ipv4_address: 172.20.0.5
    environment:
      - DB_HOST=172.20.0.10
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DOCKER_TLS_VERIFY=0

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
